#!/usr/bin/env bash
#
# Generate/Regenerate the initial RAM disk
#
# The initrd generated by debootstrap is missing several features due to
# the fact that the fstab file is missing from the target system when it is
# generated. As such, the initrd needs to be regenerated after the fstab
# has been created
set -o errexit

# Set verbose/quiet output based on env var configured in Packer template
[ "$DEBUG" = true ] && redirect="/dev/stdout" || redirect="/dev/null"

# Logging for packer
echo "Regenerating the initrd..."
LANG=C.UTF-8 chroot /target update-initramfs -u >${redirect} 2>&1

exit 0
